spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://postgres-places.c9icsi48a53s.us-east-2.rds.amazonaws.com:5432/
    username: postgres
    password: polita123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: places
server:
  port: 8082
